# SPDX-FileCopyrightText: 2025 Oliver
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: Ensure Matomo paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ matomo_uid }}"
    group: "{{ matomo_gid }}"
  with_items:
    - "{{ matomo_base_path }}"
    - "{{ matomo_data_dir_path }}"
    - "{{ matomo_config_dir_path }}"

- name: Ensure Matomo support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ matomo_base_path }}/{{ item }}"
    owner: "{{ matomo_uid }}"
    group: "{{ matomo_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure Matomo container image is pulled
  community.docker.docker_image:
    name: "{{ matomo_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matomo_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matomo_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Matomo container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ matomo_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Matomo systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matomo.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ matomo_identifier }}.service"
    mode: "0640"
