# SPDX-FileCopyrightText: 2025 Oliver
#
# SPDX-License-Identifier: GPL-3.0-or-later

---

- block:
    - when: matomo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matomo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-matomo
    - install-all
    - install-matomo

- block:
    - when: not matomo_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-matomo
