# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 MASH project contributors
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Oliver
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "matomo_config_dir_path", "new": "matomo_config_path" }
    - { "old": "matomo_data_dir_path", "new": "matomo_data_path" }
    - { "old": "matomo_http_bind_port", "new": "matomo_container_http_host_bind_port" }
    - { "old": "matomo_http_header_content_permission_policy", "new": "matomo_http_header_permissions_policy" }
    - { "old": "matomo_systemd_required_systemd_services_list", "new": "matomo_systemd_required_services_list" }
    - { "old": "matomo_systemd_required_systemd_services_list_default", "new": "matomo_systemd_required_services_list_default" }
    - { "old": "matomo_systemd_required_systemd_services_list_auto", "new": "matomo_systemd_required_services_list_auto" }
    - { "old": "matomo_systemd_required_systemd_services_list_custom", "new": "matomo_systemd_required_services_list_custom" }
    - { "old": "matomo_config_database_hostname", "new": "matomo_database_hostname" }
    - { "old": "matomo_config_database_port", "new": "matomo_database_port" }
    - { "old": "matomo_config_database_adapter", "new": "matomo_database_adapter" }
    - { "old": "matomo_config_database_tables_prefix", "new": "matomo_database_tables_prefix" }
    - { "old": "matomo_config_database_username", "new": "matomo_database_username" }
    - { "old": "matomo_config_database_password", "new": "matomo_database_password" }
    - { "old": "matomo_config_database_name", "new": "matomo_database_name" }

- name: Fail if required Matomo settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`) for using this role.
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - {'name': 'matomo_uid', when: true}
    - {'name': 'matomo_gid', when: true}
    - {'name': 'matomo_hostname', when: true}
    - {'name': 'matomo_container_network', when: true }
    - {'name': 'matomo_database_hostname', when: true}
    - {'name': 'matomo_database_username', when: true}
    - {'name': 'matomo_database_password', when: true}
    - {'name': 'matomo_container_labels_traefik_compression_middleware_name', when: "{{ matomo_container_labels_traefik_compression_middleware_enabled }}"}

- name: Run if Traefik is enabled
  when: matomo_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Matomo are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - matomo_container_labels_traefik_hostname
        - matomo_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `matomo_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if matomo_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          matomo_container_labels_traefik_path_prefix (`{{ matomo_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/matomo`).
      when: "matomo_container_labels_traefik_path_prefix != '/' and matomo_container_labels_traefik_path_prefix[-1] == '/'"
