# SPDX-FileCopyrightText: 2025 Oliver
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "matomo_config_dir_path", "new": "matomo_config_path" }
    - { "old": "matomo_data_dir_path", "new": "matomo_data_path" }
    - { "old": "matomo_http_bind_port", "new": "matomo_container_http_host_bind_port" }
    - { "old": "matomo_http_header_content_permission_policy", "new": "matomo_http_header_permissions_policy" }
    - { "old": "matomo_systemd_required_systemd_services_list", "new": "matomo_systemd_required_services_list" }
    - { "old": "matomo_systemd_required_systemd_services_list_default", "new": "matomo_systemd_required_services_list_default" }
    - { "old": "matomo_systemd_required_systemd_services_list_auto", "new": "matomo_systemd_required_services_list_auto" }
    - { "old": "matomo_systemd_required_systemd_services_list_custom", "new": "matomo_systemd_required_services_list_custom" }

- name: Fail if required matomo settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`) for using this role.
  when: "item.when | bool and (vars[item.name] is not defined or vars[item.name] | string | length == 0)"
  with_items:
    - {'name': 'matomo_hostname', when: true}
    - {'name': 'matomo_uid', when: true}
    - {'name': 'matomo_gid', when: true}
    - {'name': 'mariadb_enabled', when: true}
    - {'name': 'matomo_config_database_hostname', when: true}
    - {'name': 'matomo_config_database_username', when: true}
    - {'name': 'matomo_config_database_password', when: true}
    - {'name': 'matomo_container_labels_traefik_compression_middleware_name', when: "{{ matomo_container_labels_traefik_compression_middleware_enabled }}"}

- name: Run if Traefik is enabled
  when: matomo_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required matomo Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - matomo_container_labels_traefik_hostname
        - matomo_container_labels_traefik_path_prefix
