# SPDX-FileCopyrightText: 2025 Oliver
#
# SPDX-License-Identifier: GPL-3.0-or-later

---

- name: Fail if required matomo settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`) for using this role.
  when: "item.when | bool and (vars[item.name] is not defined or vars[item.name] | string | length == 0)"
  with_items:
    - {'name': 'matomo_hostname', when: true}
    - {'name': 'matomo_uid', when: true}
    - {'name': 'matomo_gid', when: true}
    - {'name': 'mariadb_enabled', when: true}
    - {'name': 'matomo_config_database_hostname', when: true}
    - {'name': 'matomo_config_database_username', when: true}
    - {'name': 'matomo_config_database_password', when: true}
    - {'name': 'matomo_container_labels_traefik_compression_middleware_name', when: "{{ matomo_container_labels_traefik_compression_middleware_enabled }}"}

- when: matomo_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required matomo Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - matomo_container_labels_traefik_hostname
        - matomo_container_labels_traefik_path_prefix
